### PR TITLE
Add simple Ruby server example

### LINKED ISSUE #40479: [Ruby] Create simple example of Ruby HTTP GET Arrow server
### Describe the enhancement requested

Contribute a Ruby server example to the [set of minimal HTTP GET examples in the `arrow-experiments` repo](https://github.com/apache/arrow-experiments/tree/main/http/get_simple).

### Component(s)

Ruby

### PR DESCRIPTION
**Pull request by kou**
fix apache/arrow#40479

### CODE REVIEW

**Comment by ianmcook** [comment]
Thanks @kou! 

I tested this with all the client examples. The only problem I found was with the C GLib client:

When I run the C GLib client with this this Ruby server, the server prints this message:
```
::1 - - [12/Mar/2024:09:14:43 -0400] "GET / HTTP/1.1" 200 - 0.8649
[2024-03-12 09:14:44] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:18 
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:82:in `eof?'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/webrick-1.8.1/lib/webrick/httpserver.rb:82:in `run'
	/opt/homebrew/lib/ruby/gems/3.3.0/gems/webrick-1.8.1/lib/webrick/server.rb:310:in `block in start_thread'
```

**Comment by ianmcook** [comment]
Can you add a `.gitignore` with `Gemfile.lock` please?

**Comment by kou** [comment]
Ah, it's happen because GLib client uses keep-alive and Ruby's HTTP server is sensitive for disconnection check of keep-alive connection.

I'll disable keep-alive of GLib client.

**Comment by kou** [comment]
I've add missing `.gitignore`. Good catch!

**Comment by kou** [comment]
GLib client: https://github.com/apache/arrow-experiments/pull/20

**Review by ianmcook — APPROVED** [review]
Thanks!

**Pull request merged**
