### PR TITLE
Example for Python HTTP Post Arrow client and server

### PR DESCRIPTION
**Pull request by arunppsg**
Addresses apache/arrow#40595

In this pull request, I have added an example of HTTP Post Arrow client and server.

The server uses `fastapi` for and the client uses `requests` library. Except these, the rest of the code structure is similar to the [get_simple](https://github.com/apache/arrow-experiments/tree/main/http/get_simple) example.

If there are any suggestions, feel free to let me know and I will be happy to update the PR accordingly.

### CODE REVIEW

**Comment by ianmcook** [comment]
Thank you @arunppsg! I will review this soon.

**Comment by ianmcook** [comment]
@arunppsg For the HTTP POST example, we are looking for something different than this.

As described in the [README in the `http/post_simple` directory](https://github.com/apache/arrow-experiments/tree/main/http/post_simple):

>This directory contains minimal examples of HTTP clients and servers demonstrating how a client can send a POST request to a server with a request body consisting of an Arrow IPC stream of record batches.

So in these HTTP POST examples, **the client should send the data to the server**.

However, I think this FastAPI + Uvicorn example would be a great addition to the HTTP GET examples. May I make some changes to this PR to turn it into an HTTP GET example?

**Comment by arunppsg** [comment]
> So in these HTTP POST examples, **the client should send the data to the server**.

Ah, I see - I will think about this and get back on it.
 
> However, I think this FastAPI + Uvicorn example would be a great addition to the HTTP GET examples. May I make some changes to this PR to turn it into an HTTP GET example?

Feel free to make the necessary changes for HTTP GET in this PR.

**Comment by ianmcook** [comment]
I moved the FastAPI + Uvicorn server piece of this to #37 (with some small changes).

**Pull request closed without merging**
