### PR TITLE
Add simple C GLib client example

### PR DESCRIPTION
**Pull request by kou**

### CODE REVIEW

**Comment by ianmcook** [comment]
Thanks @kou! I tested this with all the server examples and it runs without error.

Instead of destroying each `record_batch` after it is received inside the while loop, can you build up an array of pointers to the record batches so that they could be accessed after the loop is finished?

**Comment by kou** [comment]
OK. I've changed to use `GArrowTable` that is a wrapper of `arrow::Table`. It's not an array of pointers to the record batches (it's a container of chunked arrays) but they are logically same data.

If an array of pointers to the record batches is preferred, we can do it:

```diff
--- a/http/get_simple/c_glib/client/client.c
+++ b/http/get_simple/c_glib/client/client.c
@@ -53,6 +53,7 @@ main(int argc, char **argv)
   }
 
   gsize n_received_record_batches = 0;
+  GList *record_batches = NULL;
   while (TRUE) {
     GArrowRecordBatch *record_batch =
       garrow_record_batch_reader_read_next(GARROW_RECORD_BATCH_READER(reader),
@@ -60,6 +61,7 @@ main(int argc, char **argv)
     if (error) {
       g_printerr("Failed to read record batch: %s\n", error->message);
       g_error_free(error);
+      g_list_free_full(record_batches, g_object_unref);
       g_object_unref(reader);
       g_object_unref(arrow_input);
       goto exit;
@@ -67,9 +69,11 @@ main(int argc, char **argv)
     if (!record_batch) {
       break;
     }
-    g_object_unref(record_batch);
+    record_batches = g_list_prepend(record_batches, record_batch);
     n_received_record_batches++;
   }
+  record_batches = g_list_reverse(record_batches);
+  g_list_free_full(record_batches, g_object_unref);
   g_object_unref(reader);
   g_object_unref(arrow_input);
```

Which is preferred?

**Comment by ianmcook** [comment]
The `GArrowTable` approach sounds good! Thank you

**Review by ianmcook — APPROVED** [review]
Thank you @kou! I tested that the output can be written to a file ([see example](https://gist.github.com/ianmcook/30b9f58591ff6393d93afa6313ef974c#file-client-c-L80-L121)) and read in with other Arrow libraries. It all works as expected.

**Comment by kou** [comment]
Thanks for testing.
I've added a missing `g_object_unref(table)` that is included in your example.

BTW, should we add write code like you added to the example?

**Comment by ianmcook** [comment]
> Thanks for testing. I've added a missing `g_object_unref(table)` that is included in your example.

Thanks!
 
> BTW, should we add write code like you added to the example?

No, I think the examples in this `get_simple` directory should stay minimal, so it is best not to add write code.

And anyway, to write the IPC stream directly to a file, I think it would be better to write it one batch at a time inside the receive loop. What the examples in this directory all do (accumulate all the record batches in memory) is more applicable to use cases where you need to process the full data in memory after receiving it.

**Comment by kou** [comment]
OK! Can we merge this?

**Pull request merged**
